const {
  AndroidConfig,
  withAndroidManifest,
  withAppBuildGradle,
} = require('expo/config-plugins');

/**
 * Expo config plugin for expo-wacli.
 *
 * Two jobs, both Android-only. iOS needs no configuration: the XCFramework is vendored by the
 * podspec and there is nothing to declare, since the module never runs in the background and so
 * claims no background modes.
 *
 * @param {object} config
 * @param {object} [props]
 * @param {string[]} [props.abiFilters] ABIs to package. Defaults to 64-bit only.
 * @param {boolean} [props.foregroundService] Declare the foreground service permissions. Default true.
 */
module.exports = function withWacli(config, props = {}) {
  const { abiFilters = ['arm64-v8a', 'x86_64'], foregroundService = true } = props;

  if (foregroundService) {
    config = withAndroidManifest(config, (cfg) => {
      // The module's own manifest declares these too and manifest merging would pull them in, but
      // permissions that appear out of nowhere at merge time are miserable to audit. Declaring them
      // here puts them in the app manifest the developer actually reads.
      const permissions = [
        'android.permission.INTERNET',
        'android.permission.FOREGROUND_SERVICE',
        'android.permission.FOREGROUND_SERVICE_DATA_SYNC',
        'android.permission.POST_NOTIFICATIONS',
      ];
      for (const permission of permissions) {
        AndroidConfig.Permissions.ensurePermission(cfg.modResults, permission);
      }
      return cfg;
    });
  }

  if (abiFilters && abiFilters.length > 0) {
    config = withAppBuildGradle(config, (cfg) => {
      if (cfg.modResults.language !== 'groovy') {
        throw new Error(
          'expo-wacli: app/build.gradle is not Groovy; set abiFilters to null and configure ndk.abiFilters yourself.'
        );
      }
      cfg.modResults.contents = setAbiFilters(cfg.modResults.contents, abiFilters);
      return cfg;
    });
  }

  return config;
};

/**
 * The gomobile AAR carries a full copy of the Go runtime for every Android ABI — around 25 MB each,
 * four of them. Without a filter that is all packaged into a universal APK. Dropping the 32-bit
 * ABIs is nearly always right: Play has required 64-bit support since 2019, and 32-bit-only devices
 * are long past being a target worth 50 MB.
 *
 * Idempotent — re-running prebuild replaces the block rather than stacking another one.
 */
function setAbiFilters(contents, abiFilters) {
  const marker = '// @generated by expo-wacli';
  const block = [
    `        ${marker}`,
    '        ndk {',
    `            abiFilters ${abiFilters.map((abi) => `'${abi}'`).join(', ')}`,
    '        }',
  ].join('\n');

  const existing = new RegExp(`\\s*${escapeRegExp(marker)}\\n\\s*ndk \\{[^}]*\\}`, 'm');
  if (existing.test(contents)) {
    return contents.replace(existing, `\n${block}`);
  }

  // Anchor on the defaultConfig block, which every Expo-generated app/build.gradle has.
  const anchor = /(defaultConfig\s*\{)/;
  if (!anchor.test(contents)) {
    throw new Error('expo-wacli: could not find defaultConfig in app/build.gradle');
  }
  return contents.replace(anchor, `$1\n${block}`);
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
