const {
  AndroidConfig,
  withAndroidManifest,
  withGradleProperties,
} = require('expo/config-plugins');

/**
 * Expo config plugin for expo-wacli.
 *
 * Two jobs, both Android-only. iOS needs no configuration: the XCFramework is vendored by the
 * podspec and there is nothing to declare, since the module never runs in the background and so
 * claims no background modes.
 *
 * @param {object} config
 * @param {object} [props]
 * @param {string[]} [props.abiFilters] ABIs to package. Defaults to 64-bit only.
 * @param {boolean} [props.foregroundService] Declare the foreground service permissions. Default true.
 */
module.exports = function withWacli(config, props = {}) {
  const { abiFilters = ['arm64-v8a', 'x86_64'], foregroundService = true } = props;

  if (foregroundService) {
    config = withAndroidManifest(config, (cfg) => {
      // The module's own manifest declares these too and manifest merging would pull them in, but
      // permissions that appear out of nowhere at merge time are miserable to audit. Declaring them
      // here puts them in the app manifest the developer actually reads.
      const permissions = [
        'android.permission.INTERNET',
        'android.permission.FOREGROUND_SERVICE',
        'android.permission.FOREGROUND_SERVICE_DATA_SYNC',
        'android.permission.POST_NOTIFICATIONS',
      ];
      for (const permission of permissions) {
        AndroidConfig.Permissions.ensurePermission(cfg.modResults, permission);
      }
      return cfg;
    });
  }

  if (abiFilters && abiFilters.length > 0) {
    config = withGradleProperties(config, (cfg) => {
      cfg.modResults = setArchitectures(cfg.modResults, abiFilters);
      return cfg;
    });
  }

  return config;
};

/**
 * The gomobile AAR carries a full copy of the Go runtime for every Android ABI — around 25 MB each,
 * four of them. Without a filter that is all packaged into a universal APK. Dropping the 32-bit
 * ABIs is nearly always right: Play has required 64-bit support since 2019, and 32-bit-only devices
 * are long past being a target worth 50 MB.
 *
 * This is `reactNativeArchitectures` rather than the `ndk.abiFilters` block it looks like it should
 * be. `abiFilters` is a collection and its calls accumulate: React Native's own Gradle plugin adds
 * every architecture in this property, so a block naming a subset unions with that list and packages
 * all four regardless. Setting the property React Native reads is the only way to actually drop one
 * — and writing both would let them disagree, which is worse than writing neither.
 *
 * Idempotent: the existing property is replaced rather than appended to, so re-running prebuild over
 * an already-configured project does not leave two definitions with the last one silently winning.
 */
function setArchitectures(properties, abiFilters) {
  const key = 'reactNativeArchitectures';
  const marker = ' @generated by expo-wacli';

  const kept = properties.filter(
    (item) =>
      !(item.type === 'property' && item.key === key) &&
      !(item.type === 'comment' && item.value === marker)
  );

  kept.push({ type: 'comment', value: marker });
  kept.push({ type: 'property', key, value: abiFilters.join(',') });
  return kept;
}
